-- INDEX 사용하기
-- 테이블의 PRIMARY KEY로 설정된 COLUMN(속성)은 기본적이로 INDEX가 설정되어 있음
-- 예, EMP테이블의 PRIMARY KEY로 설정된 EMPNO는 INDEX가 자동 설정되어 있음
SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME IN('EMP01');

-- 인덱스 설정전과 인덱스 설정후의 조회속도 비교
DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT * FROM EMP;
INSERT INTO EMP01 SELECT * FROM EMP01;
SELECT * FROM EMP01;

INSERT INTO EMP01 (EMPNO, ENAME) VALUES(1111, 'SYJ');

-- 시간 체크하는 명령어
SET TIMING ON;
SELECT DISTINCT EMPNO, ENAME FROM EMP01 WHERE ENAME='SYJ';

-- INDEX 생성: ORACLE내부적으로 B-TREE에 대한 정보를 추가 생성
-- 생성한 INDEX를 사용하는 곳은 SELECT명령어의 WHERE 조건절 내부에서 주로 사용
-- 기본키로 설정된 속성으로 WHERE 조건절에서 사용하여 검색할 경우에는 기본적으로 속도가 매우 빠름
CREATE INDEX IDX_EMP01_ENAME ON EMP01(ENAME);

-- INDEX 삭제하기
DROP INDEX IDX_EMP01_ENAME;